### ISSUE TITLE
"default.hbs" missing

### ISSUE THREAD

**Issue by tonyin** [guovz/onepice#10]
![screen shot 2016-11-27 at 10 40 26 am](https://cloud.githubusercontent.com/assets/3144147/20650880/f9aef064-b48d-11e6-9232-f1f55c5c1810.png)

**Comment by jaylinwang** [comment]
You should move custom/*.example.hbs to custom.*.hbs, and edit the *.hbs for your config

**Comment by tonyin** [comment]
that made it work. thanks!
