### ISSUE TITLE
代码样式有问题

### ISSUE THREAD

**Issue by ghost** [guovz/onepice#11]
参考页面： http://jaylin.wang/2016/11/10/supervisor-guide/

图片：
![error](https://cloud.githubusercontent.com/assets/4003337/21883127/8b38b8a2-d8e8-11e6-9afc-814150447c79.png)

不知道是设计成这样的，还是css代码的问题，如果不是的话，希望可以修改一下，这样看着觉得有点别扭

ps：准备使用这个主题搭建自己的博客

**Comment by ghost** [comment]
我把几个css类的 overflow： scroll 去掉之后就好了， 这个属性不需要设置的

**Comment by jaylinwang** [comment]
试着提交一个PR吧，帮助更多的人 😄

**Comment by ghost** [comment]
ok， 关闭了
