### ISSUE TITLE
Ghost 0.74安装主题后chrome控制台报错

### ISSUE THREAD

**Issue by dev-techmoe** [guovz/onepice#5]
![error.png](https://ooo.0o0.ooo/2016/02/26/56d0e82bae129.png)  
就是这样。。求修复

**Comment by jaylinwang** [comment]
你需要启动ghost的beta配置呢
![image](https://cloud.githubusercontent.com/assets/4530355/13369772/40c7d1b4-dd34-11e5-88e1-66059a1b8d6a.png)
