### ISSUE TITLE
ERROR: [default.hbs] The partial custom/socials could not be found

### ISSUE THREAD

**Issue by zhishengzhang** [guovz/onepice#7]
代码家你好，应用你的主题onepice - 1.1.0,启动Ghost 出现如Title中的错误。
node v0.12.15
npm v2.15.1
Ghost v0.8.0

**Comment by jaylinwang** [comment]
custom下的文件是需要自己完成的，我在项目中提供了两个模版，socials.example.hbs和config.example.hbs,你可以参考的 😄
