### ISSUE TITLE
侧边栏无效？

### ISSUE THREAD

**Issue by Ohuisang** [guovz/onepice#9]
1.点击这两个按钮无效
![f42c1ca0-d7fe-4e83-9750-0d3d44984503](https://cloud.githubusercontent.com/assets/4980617/17972972/3263f8a6-6b13-11e6-9e1c-3b919d36899f.png)

2.在哪里设置github和微博，在页面显示？

3.首页内容不是折叠的？

**Comment by jaylinwang** [comment]
因为使用了ghost api获取第一个作者作为站点owner，所以在使用之前需要启动public api功能
![image](https://cloud.githubusercontent.com/assets/4530355/17993589/8e5d71da-6b83-11e6-92fc-1dc723281b42.png)
